<?xml version="1.0" encoding="utf-8"?>

<!--
trtoxhtml.xsl: translates techrep XML v2 to XHTML
Copyright © 2008 CESNET
Author: Ladislav Lhotka
-->


<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
		xmlns:tr="http://cesnet.cz/ns/techrep/base/2.0"
		xmlns="http://www.w3.org/1999/xhtml"
                version="1.0">

  <xsl:output indent="yes"/>

  <xsl:variable name="version">2.0</xsl:variable>

  <!-- Selection of localised terms -->

  <xsl:template name="select-local">
    <xsl:param name="cs"/>
    <xsl:param name="en"/>
    <xsl:choose>
      <xsl:when test="ancestor-or-self::*[@xml:lang='cs']">
	<xsl:value-of select="$cs"/>
      </xsl:when>
      <xsl:otherwise>
	<xsl:value-of select="$en"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <xsl:variable name="NL">
    <xsl:text>
</xsl:text>
  </xsl:variable>

  <xsl:variable name="NLNL">
    <xsl:value-of select="concat($NL,$NL)"/>
  </xsl:variable>

  <xsl:template name="xref-text">
    <xsl:if test="@raw!='true'">
      <xsl:apply-templates select="id(@linkend)"
			   mode="label"/>
      <xsl:text>&#xa0;</xsl:text>
    </xsl:if>
    <xsl:apply-templates select="id(@linkend)"
			 mode="number"/>
  </xsl:template>

  <!-- Autogenerated references
       "label" mode generates the element's label for crossrefs
       "number" mode generates the number of the matched element -->


  <xsl:template match="tr:h1|tr:h2|tr:h3" mode="label">
    <xsl:call-template name="select-local">
      <xsl:with-param name="cs">Oddíl</xsl:with-param>
      <xsl:with-param name="en">Section</xsl:with-param>
    </xsl:call-template>
  </xsl:template>

  <xsl:template match="tr:h1[not(@role='loose')]" mode="number">
    <xsl:number value="count(preceding-sibling::tr:h1[not(@role='loose')])+1"/>
    <xsl:text>.</xsl:text>
  </xsl:template>
  
  <xsl:template match="tr:h2" mode="number">
    <xsl:variable
	name="mysec"
	select="(preceding-sibling::tr:h1|preceding-sibling::tr:appendix)[last()]"/>
    <xsl:apply-templates select="$mysec" mode="number"/>
    <xsl:number
	value="count(preceding-sibling::tr:h2[preceding-sibling::tr:h1[1]=$mysec])+1"/>
    <xsl:text>.</xsl:text>
  </xsl:template>

  <xsl:template match="tr:h3" mode="number">
    <xsl:variable name="mysubsec" select="preceding-sibling::tr:h2[1]"/>
    <xsl:apply-templates select="$mysubsec" mode="number"/>
    <xsl:number
	value="count(preceding-sibling::tr:h3[preceding-sibling::tr:h2[1]=$mysubsec])+1 "/>
    <xsl:text>.</xsl:text>
  </xsl:template>

  <xsl:template match="tr:appendix" mode="label">
    <xsl:call-template name="select-local">
      <xsl:with-param name="cs">Dodatek</xsl:with-param>
      <xsl:with-param name="en">Appendix</xsl:with-param>
    </xsl:call-template>
  </xsl:template>

  <xsl:template match="tr:appendix" mode="number">
    <xsl:number format="A"/>
    <xsl:text>.</xsl:text>
  </xsl:template>
  
  <xsl:template match="tr:figure" mode="label">
    <xsl:call-template name="select-local">
      <xsl:with-param name="cs">Obrázek</xsl:with-param>
      <xsl:with-param name="en">Figure</xsl:with-param>
    </xsl:call-template>
  </xsl:template>

  <xsl:template match="tr:figure" mode="number">
    <xsl:number/>
  </xsl:template>

  <xsl:template match="tr:table" mode="label">
    <xsl:call-template name="select-local">
      <xsl:with-param name="cs">Tabulka</xsl:with-param>
      <xsl:with-param name="en">Table</xsl:with-param>
    </xsl:call-template>
  </xsl:template>

  <xsl:template match="tr:table"
		mode="number">
    <xsl:number value="count(preceding-sibling::tr:table)+1"/>
  </xsl:template>

  <xsl:template match="tr:ol/tr:li" mode="label">
    <xsl:call-template name="select-local">
      <xsl:with-param name="cs">položka</xsl:with-param>
      <xsl:with-param name="en">item</xsl:with-param>
    </xsl:call-template>
  </xsl:template>

  <xsl:template match="tr:bibitem" mode="number">
    <xsl:number/>
  </xsl:template>

  <xsl:template match="tr:footnote" mode="number">
    
  </xsl:template>

  <!-- Root element -->

  <xsl:template match="/">
    <html>
      <head>
	<meta http-equiv="Content-Type" content="text/html"
	      charset="utf-8"/>
	<meta name="generator"
	      content="trtoxhtml {$version}"/>
	<title>
	  <xsl:value-of select="tr:report/tr:title"/>
	</title>
      </head>
      <body>
	<xsl:apply-templates select="tr:report"/>
      </body>
    </html>
  </xsl:template>

  <xsl:template match="@xml:id">
    <xsl:element name="a">
      <xsl:attribute name="name">
	<xsl:value-of select="."/>
      </xsl:attribute>
    </xsl:element>
  </xsl:template>

  <xsl:template match="tr:report">
    <xsl:apply-templates select="tr:title"/>
    <p>
      <strong>
	<xsl:call-template name="select-local">
	  <xsl:with-param name="cs">Technická zpráva</xsl:with-param>
	  <xsl:with-param name="en">Technical report</xsl:with-param>
	</xsl:call-template>
	<xsl:text>&#xa0;</xsl:text>
	<xsl:value-of select="@number"/>
      </strong>
    </p>
    <p>
      <big><strong>
	<xsl:for-each select="tr:author">
	  <xsl:value-of select="tr:name"/>
	  <xsl:if test="position() != last()">
	    <xsl:text>, </xsl:text>
	  </xsl:if>
	</xsl:for-each>
      </strong></big>
	<br/>
      <big><strong>
	<xsl:value-of select="tr:date"/>
      </strong></big>
    </p>
    <xsl:apply-templates select="tr:abstract"/>
    <xsl:apply-templates select="tr:keywords"/>
    <xsl:apply-templates select="tr:body"/>
  </xsl:template>

  <xsl:template match="tr:title">
    <h1><xsl:apply-templates/></h1>
  </xsl:template>

  <xsl:template match="tr:abstract">
    <h2>
      <xsl:call-template name="select-local">
	<xsl:with-param name="cs">Abstrakt</xsl:with-param>
	<xsl:with-param name="en">Abstract</xsl:with-param>
      </xsl:call-template>
    </h2>
    <xsl:apply-templates/>
  </xsl:template>

  <xsl:template match="tr:keywords">
    <p><strong>
      <xsl:call-template name="select-local">
	<xsl:with-param name="cs">Klíčová slova</xsl:with-param>
	<xsl:with-param name="en">Keywords</xsl:with-param>
      </xsl:call-template>
    </strong><xsl:apply-templates/></p>
  </xsl:template>

  <xsl:template match="tr:body">
    <xsl:apply-templates/>
  </xsl:template>

  <xsl:template match="tr:h1">
    <h2>
      <xsl:apply-templates select="." mode="number"/>
      <xsl:text>&#xA0;</xsl:text>
      <xsl:apply-templates/>
    </h2>
  </xsl:template>

  <xsl:template match="tr:h2">
    <h3>
      <xsl:apply-templates select="." mode="number"/>
      <xsl:text>&#xA0;</xsl:text>
      <xsl:apply-templates/>
    </h3>
  </xsl:template>

  <xsl:template match="tr:h3">
    <h4>
      <xsl:apply-templates select="." mode="number"/>
      <xsl:text>&#xA0;</xsl:text>
      <xsl:apply-templates/>
    </h4>
  </xsl:template>

  <xsl:template match="tr:appendix">
    <h2>
      <xsl:text>Appendix&#xA0;</xsl:text>
      <xsl:apply-templates select="." mode="number"/>
      <xsl:text>&#xA0;</xsl:text>
      <xsl:apply-templates/>
    </h2>
  </xsl:template>

  <xsl:template match="tr:p|tr:pre|tr:ol|tr:ul|tr:dl|tr:dd|tr:li">
    <xsl:element name="{local-name()}">
      <xsl:apply-templates select="@xml:id"/>
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>

  <xsl:template match="tr:strong|tr:sup|tr:sub|tr:blockquote">
    <xsl:element name="{local-name()}">
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>

  <xsl:template match="tr:dt">
    <xsl:element name="dt">
      <xsl:element name="strong">
	<xsl:apply-templates/>
      </xsl:element>
    </xsl:element>
  </xsl:template>

  <xsl:template match="tr:em|tr:command|tr:file|tr:uri|tr:phrase">
    <em><xsl:apply-templates/></em>
  </xsl:template>

  <xsl:template match="tr:tt|tr:input">
    <code><xsl:apply-templates/></code>
  </xsl:template>

  <xsl:template match="tr:q">
    <xsl:choose>
      <xsl:when test="ancestor-or-self::*[@xml:lang='cs']">
	<xsl:text>„</xsl:text>
	<xsl:apply-templates/>
	<xsl:text>“</xsl:text>
      </xsl:when>
      <xsl:otherwise>
	<xsl:text>“</xsl:text>
	<xsl:apply-templates/>
	<xsl:text>”</xsl:text>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <xsl:template match="tr:a">
    <xsl:element name="a">
      <xsl:attribute name="href">
	<xsl:value-of select="@href"/>
      </xsl:attribute>
      <xsl:apply-templates/>
    </xsl:element>
  </xsl:template>

  <xsl:template match="footnote">
    <xsl:variable name="fnnum">
      <xsl:number count="footnote" level="any"/>
    </xsl:variable>
    <a>
      <xsl:attribute name="href">
	<xsl:value-of select="concat('#poznamka_',$fnnum)"/>
      </xsl:attribute>
      <sup>
	<xsl:value-of select="$fnnum"/>
      </sup>
    </a>
  </xsl:template>

</xsl:stylesheet>

