<?xml version="1.0" encoding="utf-8"?>

<!--

trto-lib.xsl - common XSLT templates for Techrep2 -> XHTML, TeX
Copyright © 2010 CESNET
Author: Ladislav Lhotka <Lhotka@cesnet.cz>

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

-->

<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
		xmlns:tr="http://cesnet.cz/ns/techrep/base/2.0"
                version="1.0">

  <!-- Selection of localised terms -->

  <xsl:template name="select-local">
    <xsl:param name="cs"/>
    <xsl:param name="en"/>
    <xsl:choose>
      <xsl:when test="ancestor-or-self::tr:*[@xml:lang='cs']">
	<xsl:value-of select="$cs"/>
      </xsl:when>
      <xsl:otherwise>
	<xsl:value-of select="$en"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- Autogenerated references
       "label" mode generates the element's label for crossrefs
       "number" mode generates the number of the matched element -->

  <xsl:template match="tr:h1|tr:h2|tr:h3" mode="label">
    <xsl:call-template name="select-local">
      <xsl:with-param name="cs">Oddíl</xsl:with-param>
      <xsl:with-param name="en">Section</xsl:with-param>
    </xsl:call-template>
  </xsl:template>

  <xsl:template match="tr:h1[not(@role='loose')]" mode="number">
    <xsl:number value="count(preceding-sibling::tr:h1[not(@role='loose')])+1"/>
  </xsl:template>
  
  <xsl:template match="tr:h2" mode="number">
    <xsl:variable
	name="mysec"
	select="(preceding-sibling::tr:h1
		|preceding-sibling::tr:appendix)[last()]"/>
    <xsl:apply-templates select="$mysec" mode="number"/>
    <xsl:text>.</xsl:text>
    <xsl:number
	value="count(preceding-sibling::tr:h2
	       [preceding-sibling::tr:h1[1]=$mysec])+1"/>
  </xsl:template>

  <xsl:template match="tr:h3" mode="number">
    <xsl:variable name="mysubsec" select="preceding-sibling::tr:h2[1]"/>
    <xsl:apply-templates select="$mysubsec" mode="number"/>
    <xsl:text>.</xsl:text>
    <xsl:number
	value="count(preceding-sibling::tr:h3
	       [preceding-sibling::tr:h2[1]=$mysubsec])+1 "/>
  </xsl:template>

  <xsl:template match="tr:appendix" mode="label">
    <xsl:call-template name="select-local">
      <xsl:with-param name="cs">Dodatek</xsl:with-param>
      <xsl:with-param name="en">Appendix</xsl:with-param>
    </xsl:call-template>
  </xsl:template>

  <xsl:template match="tr:appendix" mode="number">
    <xsl:number format="A"/>
  </xsl:template>
  
  <xsl:template match="tr:figure" mode="label">
    <xsl:call-template name="select-local">
      <xsl:with-param name="cs">Obrázek</xsl:with-param>
      <xsl:with-param name="en">Figure</xsl:with-param>
    </xsl:call-template>
  </xsl:template>

  <xsl:template match="tr:figure|tr:table" mode="number">
    <xsl:number/>
  </xsl:template>

  <xsl:template match="tr:table" mode="label">
    <xsl:call-template name="select-local">
      <xsl:with-param name="cs">Tabulka</xsl:with-param>
      <xsl:with-param name="en">Table</xsl:with-param>
    </xsl:call-template>
  </xsl:template>

  <xsl:template match="tr:ol/tr:li" mode="label">
    <xsl:call-template name="select-local">
      <xsl:with-param name="cs">položka</xsl:with-param>
      <xsl:with-param name="en">item</xsl:with-param>
    </xsl:call-template>
  </xsl:template>

  <xsl:template match="tr:ol/tr:li" mode="number">
    <xsl:variable name="prev">
      <xsl:choose>
	<xsl:when test="../@continue">
	  <xsl:apply-templates select="id(../@continue)"
			       mode="itemcount"/>
	</xsl:when>
	<xsl:otherwise>0</xsl:otherwise>
      </xsl:choose>
    </xsl:variable>
    <xsl:variable name="this">
      <xsl:number/>
    </xsl:variable>
    <xsl:value-of select="$prev+$this"/>
  </xsl:template>

  <xsl:template match="tr:bibitem" mode="number">
    <xsl:text>[</xsl:text>
    <xsl:number/>
    <xsl:text>]</xsl:text>
  </xsl:template>

</xsl:stylesheet>
